// The *only* allowed Groq call site in the codebase (per Key Files Map) —
// research.worker.ts and writer.worker.ts both call into this module rather
// than hitting the Groq API directly, so mocking/auth/base-URL concerns
// stay in one place.
import { env } from "./env";

const GROQ_BASE_URL = "https://api.groq.com/openai/v1";

// The only two ways the mock path can activate — both explicit, neither
// inferred from APP_ENV or from a missing GROQ_API_KEY (see lib/env.ts).
// This keeps the mock available for automated tests without ever letting
// dev or prod silently fall back to it.
function isMockMode(): boolean {
  return env.NODE_ENV === "test" || env.USE_MOCK_LLM;
}

// Fixed canned response returned instead of a real API call whenever
// isMockMode() is true — this is what lets automated tests run the full
// research/write pipeline with zero Groq quota usage and no network
// dependency.
const MOCK_COMPLETION = `## Local ARAP response

This response was generated by the local Groq mock. No hosted LLM API was called.`;

type ChatMessage = {
  role: "system" | "user" | "assistant";
  content: string;
};

interface ChatCompletionResponse {
  choices: Array<{
    message: {
      content: string;
    };
  }>;
}

interface ChatCompletionStreamChunk {
  choices?: Array<{
    delta?: {
      content?: string;
    };
  }>;
}

// Shared non-streaming request helper (used by createCompletion; the
// streaming path below has its own fetch call since it needs to read the
// response as a byte stream instead of parsing one JSON body).
async function groqRequest<T>(path: string, body: unknown): Promise<T> {
  const response = await fetch(`${GROQ_BASE_URL}${path}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${env.GROQ_API_KEY ?? ""}`,
    },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const message = await response.text();
    throw new Error(`Groq request failed (${response.status}): ${message}`);
  }

  return (await response.json()) as T;
}

// Non-streaming completion — used where the full text is needed at once
// (e.g. the research summary passed whole into the writer job) rather than
// token-by-token.
export async function createCompletion(
  messages: ChatMessage[],
): Promise<string> {
  if (isMockMode()) {
    return MOCK_COMPLETION;
  }

  const payload = {
    model: "llama-3.3-70b-versatile",
    messages,
    temperature: 0.2,
  };

  const result = await groqRequest<ChatCompletionResponse>(
    "/chat/completions",
    payload,
  );
  return result.choices[0]?.message?.content ?? "";
}

// Streaming completion — an async generator that yields tokens as they
// arrive, which the research/writer workers forward one-by-one into Redis
// pub/sub (see publishSessionEvent "token" events) so the browser sees
// text appear incrementally instead of waiting for the whole response.
export async function* streamCompletion(
  messages: ChatMessage[],
): AsyncGenerator<string> {
  if (isMockMode()) {
    // Mimics real token streaming by splitting the mock text on whitespace
    // (keeping the whitespace itself via capturing group + filter) so
    // consumers see the same shape of incremental chunks they'd get live.
    for (const token of MOCK_COMPLETION.split(/(\s+)/).filter(Boolean)) {
      yield token;
    }
    return;
  }

  const response = await fetch(`${GROQ_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${env.GROQ_API_KEY ?? ""}`,
    },
    body: JSON.stringify({
      model: "llama-3.3-70b-versatile",
      messages,
      temperature: 0.2,
      stream: true,
    }),
  });

  if (!response.ok) {
    const message = await response.text();
    throw new Error(`Groq request failed (${response.status}): ${message}`);
  }

  if (!response.body) {
    throw new Error("Groq streaming response did not include a body");
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  // Groq's streaming format is OpenAI-compatible SSE: each event is a
  // "data: {...}" line, terminated by a final "data: [DONE]" sentinel.
  const parseLine = (line: string): string | null => {
    const trimmed = line.trim();
    if (!trimmed.startsWith("data:")) {
      return null;
    }

    const data = trimmed.slice("data:".length).trim();
    if (data === "[DONE]") {
      return "[DONE]";
    }

    const parsed = JSON.parse(data) as ChatCompletionStreamChunk;
    return parsed.choices?.[0]?.delta?.content ?? null;
  };

  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }

    // Network chunks don't align with line boundaries, so decoded text
    // accumulates in `buffer`; only fully-terminated lines are parsed each
    // pass, and the trailing partial line is kept in the buffer for the
    // next read.
    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split(/\r?\n/);
    buffer = lines.pop() ?? "";

    for (const line of lines) {
      const token = parseLine(line);
      if (token === "[DONE]") {
        return;
      }
      if (token) {
        yield token;
      }
    }
  }

  // Flush whatever's left in the decoder/buffer after the stream ends, in
  // case the final line arrived without a trailing newline.
  buffer += decoder.decode();
  for (const line of buffer.split(/\r?\n/)) {
    const token = parseLine(line);
    if (token === "[DONE]") {
      return;
    }
    if (token) {
      yield token;
    }
  }
}
